# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emerson MX
email: emersonmx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um simples diário de um programador
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://www.emersonmx.com.br' # the base hostname & protocol for your site, e.g. http://example.com
lang: pt-BR
social:
  twitter:
    username: emersonmx
  github:
    username: emersonmx
facebook:
  app_id: 1676678679285537
defaults:
  - scope:
      path: ''
    values:
      image: /assets/img/facebook.png

permalink: /:categories/:title/
paginate: 5
paginate_path: '/page:num/'
date_format: '%Y-%m-%d %H:%M'
excerpt_separator: '<!--more-->'

# Prose settings
prose:
  siteurl: 'http://www.emersonmx.com.br/'
  relativeLinks: 'http://www.emersonmx.com.br/links.jsonp'
  media: 'files'
  ignore:
    - /_data
    - /_includes
    - /_layouts
    - /_sass
    - /_scripts
    - /.gitignore
    - /CNAME
    - /Gemfile*
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: 'title'
        field:
          element: 'text'
          label: 'Título'
          value: ''
      - name: 'category'
        field:
          element: 'select'
          label: 'Categoria'
          placeholder: 'Seleciona a categoria'
          options:
            - name: 'Engenharia de Software'
              value: 'engenharia-de-software'
            - name: 'Programação'
              value: 'programacao'
            - name: 'Projetos'
              value: 'projetos'
            - name: 'RNG'
              value: 'rng'
            - name: 'SFML Series'
              value: 'sfml-series'
      - name: 'tags'
        field:
          element: 'multiselect'
          label: 'Tags'
          placeholder: 'Selecione as tags'
          options:
            - name: 'Box2D'
              value: 'box2d'
            - name: 'C'
              value: 'c'
            - name: 'CPP'
              value: 'cpp'
            - name: 'Curiosidades'
              value: 'curiosidades'
            - name: 'Dicas'
              value: 'dicas'
            - name: 'PHP'
              value: 'php'
            - name: 'Python'
              value: 'python'
            - name: 'RNG'
              value: 'rng'
            - name: 'Série'
              value: 'serie'
            - name: 'SFML'
              value: 'sfml'
            - name: 'Vim'
              value: 'vim'
      - name: 'splash'
        field:
          element: 'text'
          label: 'Imagem de destaque'
          value: ''
    _posts/static:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'page'
      - name: 'title'
        field:
          element: 'text'
          label: 'Título'
          value: ''
      - name: 'permalink'
        field:
          element: 'text'
          label: 'Permalink'
          value: ''

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginage
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.mix.js
  - node_modules/
  - mix-manifest.json
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

timezone: America/Fortaleza
safe: true
